pipeline:
  build:
    image: golang:1.9
    commands:
      - cd src && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o docker-deploy
      - ls
  
  publish:
    image: registry.wesense.cloud/docker-deploy
    pull: true
    registry: registry.wesense.cloud
    image: registry.wesense.cloud/docker-deploy
    secrets: [ docker_username, docker_password ]
    commands:
      - env
    when:
      branch: master
  
  # publish:
  #   image: plugins/docker
  #   dockerfile: Dockerfile
  #   registry: registry.wesense.cloud
  #   repo: registry.wesense.cloud/docker-deploy
  #   secrets: [ docker_username, docker_password ]
  #   tags: [ latest ]
  #   when:
  #     branch: master