workspace:
  base: /go
  path: src/github.com/schrodit/drone-docker-deploy

pipeline:

  deps:
    image: golang:1.9
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  
  test:
    image: golang:1.9
    commands:
      - go test -cover

  build:
    image: golang:1.9
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -o docker-deploy
      - ls
  
  # publish:
  #   image: plugins/docker
  #   dockerfile: Dockerfile
  #   repo: schrodit/drone-docker-deploy
  #   secrets: [ docker_username, docker_password ]
  #   tags: [ latest ]
  #   when:
  #     branch: master

  publish:
    image: schrodit/drone-docker-deploy
    pull: true
    repo: schrodit/drone-docker-deploy
    secrets: [ docker_username, docker_password ]
    usegittag: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    when:
      event: [push, tag]
      branch: master